### PR TITLE
Add bot support

### PR DESCRIPTION
**Pull request by selesse**
Hi!

I see you noticed my commit. I have a couple of things I'd like to verify with you before I formally send a PR (this one is a work-in-progress).

### Cisco Spark Library Change

If possible, I would like to change the underlying Spark library to the [official Cisco Spark one](https://github.com/ciscospark/spark-js-sdk). To do that, I was planning on introducing a "SparkApi" class to abstract away the implementation (`csco-spark` vs `ciscospark`). Once the class was there, as a separate commit, I'd swap out the underlying implementation. The problem with switching to the official Cisco Spark API is that they don't have an API for `/people/me` (at least none that I could find in [their documentation](https://ciscospark.github.io/spark-js-sdk/api/#CiscoSpark)), which is critical for bot support. I'd have to implement that request myself (as I've currently done in this PR).

The other thing I don't like about doing this is that we'd be losing support for the `HUBOT_SPARK_API_URI` environment variable (which I've personally found handy).

### csco-spark issues

If we stick with csco-spark, I'd have to send a PR to add support for customizing the `getMessages` API call to support `mentionedPeople` (since the API restricts bot access so they can only get messages where they are mentioned), and `/people/me`. I'd like to (ideally) avoid doing the requests in *this* library so that there's more consistent/better support for things like proxies.

What do you think? :)

### CODE REVIEW

**Comment by tonybaloney** [comment]
Changes look great, I'm new to coffeescript so it's good to see the code cleaned up too. 

Wrt to csco-spark v.s. ciscospark, this is one of the first issues #2 raised, I looked and couldn't see an important feature, the ability to list messages since a specific datestamp. Without that your bot will be eating memory and paging out messages in a room. It was also closed source, I asked at the time and the product team said they were planning to open it up once they refactored it. 
That now seems to have happened https://github.com/ciscospark/spark-js-sdk/ so I'm happy to move over, but as you say it's missing some functions. Are you sure you can get messages since date? https://ciscospark.github.io/spark-js-sdk/api/#Messages

An extension class makes sense, maybe just add the extra params in there. 

I can't see how you specify a private URL in the ciscospark module either. that seems odd. we should ask the spark devs.

**Comment by tonybaloney** [comment]
@selesse apparently if you set the people ID to "me" it will fetch `/people/me`

**Comment by selesse** [comment]
Interesting! Looking into it right now, thanks :)

**Comment by selesse** [comment]
So swapping the implementation was pretty straightforward (https://github.com/Stack8/hubot-spark/compare/add-bot-support...official-ciscospark-api?expand=1) - I'm done! :)

I still have a few concerns though.

1. We'd be dropping support for the `HUBOT_SPARK_API_URI` environment variable. I dug around some more but still didn't find anything for replacing that.
2. When I was looking at the current implementation, I noticed we're not actually asking for messages since a particular timestamp. Every 10 seconds, we ask for the last 200 messages, and we _locally_ filter the messages. It seems like it should be asking for only the messages it hasn't yet received. This PR preserves the existing behavior.
3. Longer-term, I believe Cisco has plans to release a WebSocket API for Spark. Instead of polling every 10 seconds, it would be much better to rely on sockets/events. I've used this library (https://github.com/marchfederico/ciscospark-websocket-events) and it seems like it would make a great addition/replacement to the current implementation.

What do you think? :)

**Comment by selesse** [comment]
Ahh yes, one more thing (sorry):

Passing in a list of room IDs to listen to is a bit problematic if you expect Hubot to be able to respond to DMs. You'd have to programmatically determine the room IDs of all the DMs that are being opened every few seconds? I'm not even sure. Swapping to the websocket-event library solves this problem. :)

**Comment by akalsey** [comment]
> support for the HUBOT_SPARK_API_URI environment variable.

Setting an environment variable called `HYDRA_SERVICE_URL` to the API URL you want to use should do it. You can also mess around with the object you get back after you require('ciscospark'). There's a config key there that has a property of hydraServiceUrl that sets the URL. When the object is created, it sets that property to the environment variable if it exists, or defaults to `https://api.ciscospark.com/v1`

> It seems like it should be asking for only the messages it hasn't yet received.

The Spark API doesn't currently support an *after* parameter on the messages API.

**Comment by selesse** [comment]
Oh, whoops - I forgot that *before* and *after* weren't the same thing ;).

I've fixed the `HUBOT_SPARK_API_URI` environment variable [here](https://github.com/Stack8/hubot-spark/commit/3d57f46d6389099d7bbc34075d4ba8f5f4cc4336), thanks for your suggestion!

**Comment by tonybaloney** [comment]
@selesse I've asked about a WebSocket API plenty of times. I could never find a parameter to filter the messages it hasn't yet received. There _should_ be a `rooms/messages/?afterMessage=1234` or timestamp filter at the very least.
Everyone else is using WebHooks since they're easier for non-developers but it means your bot has to run on a public IP, which gives me nightmares

Another implementation I did (Python), I just add the "read" messages to a list. Which is obviously horrible!

**Comment by tonybaloney** [comment]
FWIW I think we should merge this in and resolve the paging seperately.

**Comment by selesse** [comment]
Agreed!

I'll make a separate PR for switching to `ciscospark`.

**Comment by tonybaloney** [comment]
So ok to merge @selesse ?

**Comment by selesse** [comment]
Yep! :)

**Comment by tonybaloney** [comment]
:+1:

**Pull request merged**
